---
title: "Eksploracja danych geoprzestrzennych"
subtitle: "Klasyfikacja nienadzorowana"
author: "Krzysztof Dyba"
format:
  html:
    toc: true
    toc-title: " "
    embed-resources: true
    code-links:
      - text: Repozytorium
        icon: github
        href: https://github.com/kadyb/edg2025
---

1. Materiały: <https://kadyb.github.io/GEOINF2022/Grupowanie.html>
2. Dane: <https://zenodo.org/records/7299645>

# Zadanie

Dokonaj klasyfikacji nienadzorowanej danych rastrowych znajdujących się w
katalogu `dane` (w repozytorium GitHub) używając metody `k-means`. Pamiętaj,
że ta metoda jest wrażliwa na skalę zmiennych wejściowych. Raport musi zawierać
następujące elementy:

- Porównanie wyników dla różnej liczby klastrów.
- Porównanie z inną wybraną metodą, np. *Gaussian mixture models* (pakiet `mclust`).
- Weryfikacja jakości klasyfikacji za pomocą wskaźnika *silhouette* na losowej
próbie.
- Wizualizacja wyników na mapie z odpowiednio dobraną paletą barw.
- Interpretacja  i etykietowanie wydzielonych klastrów na podstawie analizy
wykresu pudełkowego (wybierz tylko jeden przykład klasyfikacji).

Jako rozwiązanie należy przesłać:

- Działający plik źródłowy (np. Quarto `.qmd` lub RMarkdown `.Rmd`).
- Wygenerowany raport z wynikami przeprowadzonej analizy, rycinami oraz wnioskami
(np. `.html` lub `.pdf`). Uwaga: Jeśli generujesz raport w formacie `.html`, to
pamiętaj osadzić wszystkie niezbędne pliki.
