---
title: "Eksploracja danych geoprzestrzennych"
subtitle: "Klasyfikacja nadzorowana"
author: "Krzysztof Dyba"
format:
  html:
    toc: true
    toc-title: " "
    embed-resources: true
    code-links:
      - text: Repozytorium
        icon: github
        href: https://github.com/kadyb/edg2025
---

1. Materiały: <https://kadyb.github.io/GEOINF2022/Klasyfikacja.html>
2. Dane: <https://zenodo.org/records/7299645>

# Zadanie

Dokonaj klasyfikacji nadzorowanej danych rastrowych znajdujących się w katalogu
`dane` (w repozytorium GitHub) używając algorytmu drzewa decyzyjnego oraz
losowego podziału na zbiór treningowy i testowy. Jako dane referencyjne
wykorzystaj klasy użytkowania terenu. Raport musi zawierać następujące elementy:

- Obliczenie procentowego udziału poszczególnych klas na analizowanym obszarze.
Czy klasy są zbalansowane?
- Interpretacja decyzji klasyfikacyjnych podejmowanych przez model. Które
zmienne okazały się być kluczowe do rozróżnienia klas?
- Ogólna ocena skuteczności wytrenowanego modelu na zbiorze testowym. Wskaż
również, które klasy były najczęściej mylone na podstawie macierzy błędów.
- Wizualne porównanie wyników klasyfikacji z mapą referencyjną (użyj
identycznego schematu kolorów).

Jako rozwiązanie należy przesłać:

- Działający plik źródłowy (np. Quarto `.qmd` lub RMarkdown `.Rmd`).
- Wygenerowany raport z wynikami przeprowadzonej analizy, rycinami oraz wnioskami
(np. `.html` lub `.pdf`). Uwaga: Jeśli generujesz raport w formacie `.html`, to
pamiętaj osadzić wszystkie niezbędne pliki.
